<a href="https://colab.research.google.com/github/darshilsaboo1401/Feature-Engineering/blob/main/Encoding_a_Categorical_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ORDINAL & LABEL ENCODING (ORDINAL CATEGORICAL DATA)

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('/content/customer.csv')

In [3]:
df.sample(5)

    age  gender   review education purchased
37   94    Male  Average        PG       Yes
0    30  Female  Average    School        No
47   38  Female     Good        PG       Yes
27   69  Female     Poor        PG        No
11   74    Male     Good        UG       Yes

In [4]:
df=df.iloc[:,2:]

In [5]:
df

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [6]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [8]:
x_train

     review education
29  Average        UG
3      Good        PG
25     Good    School
19     Poor        PG
28     Poor    School
31     Poor    School
4   Average        UG
0   Average    School
14     Poor        PG
15     Poor        UG
8   Average        UG
38     Good    School
7      Poor    School
1      Poor        UG
6      Good    School
30  Average        UG
46     Poor        PG
43     Poor        PG
35     Poor    School
10     Good        UG
24  Average        PG
2      Good        PG
11     Good        UG
13  Average    School
20  Average    School
49     Good        UG
47     Good        PG
5   Average    School
40     Good    School
9      Good        UG
37  Average        PG
32  Average        UG
27     Poor        PG
48     Good        UG
39     Poor        PG
21  Average        PG
16     Poor        UG
44  Average        UG
12     Poor    School
26     Poor        PG

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [11]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [22]:
# Re-split to restore x_train and x_test to their DataFrame state
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 0:2], df.iloc[:, -1], test_size=0.2)

# Re-fit the encoder on the freshly restored x_train to register both features
oe.fit(x_train)

# Transform using new variables to avoid overwriting original data
x_train_transformed = oe.transform(x_train)
x_test_transformed = oe.transform(x_test)

In [24]:
x_train_transformed

array([[2., 0.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [2., 0.],
       [1., 2.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [0., 0.],
       [0., 2.]])

In [25]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
le=LabelEncoder()

In [28]:
le.fit(y_train)

LabelEncoder()

In [29]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [30]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [31]:
y_train

array([0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0])

ONE HOT ENCODING(NOMINAL CATEGORICAL DATA)

In [32]:
import numpy as np
import pandas as pd

In [33]:
df=pd.read_csv('/content/cars.csv')

In [34]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [35]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [36]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [37]:
df['fuel'].nunique()

4

In [38]:
df['brand'].nunique()

32

In [40]:
# one hot encoding using pandas
pd.get_dummies(df,columns=['fuel','owner'],dtype=int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

In [41]:
# multicollinearity problem ko hatana/ k-1 one hot encoding
pd.get_dummies(df,columns=['fuel','owner'],dtype=int,drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

In [42]:
# pandas har barr columns ka numbers badal kr dega isloye scikit learn ki ek library use krte h naam h onehotencode
# one hot encoding using sklearn
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [43]:
x_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [46]:
x_test.head()

         brand  km_driven    fuel         owner
606    Hyundai      80000  Petrol   First Owner
7575  Mahindra      70000  Diesel  Second Owner
7705    Toyota      68089  Petrol   First Owner
4305   Hyundai      70000  Petrol  Second Owner
2685  Mahindra      97000  Diesel  Second Owner

In [47]:
from sklearn.preprocessing import OneHotEncoder

In [78]:
ohe=OneHotEncoder(drop='first',dtype=np.int32)

In [79]:
x_train_new=ohe.fit_transform(x_train[['fuel','owner']]).toarray()

In [80]:
x_test_new=ohe.transform(x_test[['fuel','owner']]).toarray()

In [81]:
x_train_new.shape

(6502, 7)

In [82]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

In [83]:
# one hot encoding with top categories

In [85]:
counts=df['brand'].value_counts()

In [86]:
df['brand'].nunique()
threshold=100

In [88]:
repl=counts[counts<=threshold].index

In [91]:
pd.get_dummies(df['brand'].replace(repl,'uncommon'),dtype=int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
1973,0,0,0,0,0,0,1,0,0,0,0,0,0
3157,0,0,0,0,0,0,0,0,0,1,0,0,0
4180,0,0,0,0,0,1,0,0,0,0,0,0,0
5763,0,0,0,0,1,0,0,0,0,0,0,0,0
744,0,0,0,0,0,1,0,0,0,0,0,0,0

COLUMN TRANFORMER

In [92]:
import numpy as np
import pandas as pd

In [93]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [94]:
df=pd.read_csv('/content/covid_toy.csv')

In [95]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [96]:
 from sklearn.model_selection import train_test_split
 x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [97]:
x_train

    age  gender  fever   cough       city
60   24  Female  102.0  Strong  Bangalore
70   68  Female  101.0  Strong      Delhi
61   81  Female   98.0  Strong     Mumbai
54   60  Female   99.0    Mild     Mumbai
92   82  Female  102.0  Strong    Kolkata
..  ...     ...    ...     ...        ...
50   19    Male  101.0    Mild      Delhi
32   34  Female  101.0  Strong      Delhi
38   49  Female  101.0    Mild      Delhi
39   50  Female  103.0    Mild    Kolkata
6    14    Male  101.0  Strong  Bangalore

[80 rows x 5 columns]

In [98]:
# adding simple imputer to feever col
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])
x_test_fever=si.fit_transform(x_test[['fever']])

x_train_fever.shape

(80, 1)

In [99]:
# ordinal encoding->cough
oe=OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[['cough']])
x_test_cough=oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [101]:
# one hot encoding ->gender,city
ohe=OneHotEncoder(drop='first')
x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city=ohe.fit_transform(x_test[['gender','city']])

x_train_gender_city.shape

(80, 4)

In [102]:
# ectracting age
x_train_age=x_train.drop(columns=['gender','fever','cough','city']).values
x_test_age=x_test.drop(columns=['gender','fever','cough','city']).values

x_train_age.shape

(80, 1)

In [104]:
# Convert the sparse one-hot encoded matrices to dense numpy arrays
x_train_transformed = np.concatenate((x_train_age, x_train_fever, x_train_gender_city.toarray(), x_train_cough), axis=1)
x_test_transformed = np.concatenate((x_test_age, x_test_fever, x_test_gender_city.toarray(), x_test_cough), axis=1)

x_train_transformed.shape

(80, 7)

In [ ]:
# using column tranformer

In [105]:
from sklearn.compose import ColumnTransformer

In [106]:
transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop='first'),['gender','city'])
],remainder='passthrough')

In [108]:
transformer.fit_transform(x_train).shape

(80, 7)

In [109]:
transformer.transform(x_test).shape

(20, 7)